/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nfe_xml;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.Attr;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;

/**
 *
 * @author higor
 */
public class FormMenu extends javax.swing.JFrame 
{

    /**
     * Creates new form FormMenu
     */
    public FormMenu() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cNF = new javax.swing.JCheckBox();
        natOp = new javax.swing.JCheckBox();
        mod = new javax.swing.JCheckBox();
        serie = new javax.swing.JCheckBox();
        nNF = new javax.swing.JCheckBox();
        dhEmi = new javax.swing.JCheckBox();
        idDest = new javax.swing.JCheckBox();
        dhSaiEnt = new javax.swing.JCheckBox();
        tpNF = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        indFinal = new javax.swing.JCheckBox();
        indPres = new javax.swing.JCheckBox();
        cMunFG = new javax.swing.JCheckBox();
        tpImp = new javax.swing.JCheckBox();
        tpEmis = new javax.swing.JCheckBox();
        cDV = new javax.swing.JCheckBox();
        tpAmb = new javax.swing.JCheckBox();
        finNFe = new javax.swing.JCheckBox();
        procEmi = new javax.swing.JCheckBox();
        verProc = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        cProd = new javax.swing.JCheckBox();
        cEAN = new javax.swing.JCheckBox();
        xProd = new javax.swing.JCheckBox();
        NCM = new javax.swing.JCheckBox();
        CEST = new javax.swing.JCheckBox();
        CFOP = new javax.swing.JCheckBox();
        qCom = new javax.swing.JCheckBox();
        vUnCom = new javax.swing.JCheckBox();
        vProd = new javax.swing.JCheckBox();
        cEANTrib = new javax.swing.JCheckBox();
        uTrib = new javax.swing.JCheckBox();
        qTrib = new javax.swing.JCheckBox();
        uCom = new javax.swing.JCheckBox();
        vUnTrib = new javax.swing.JCheckBox();
        indTot = new javax.swing.JCheckBox();
        btnEnviar = new javax.swing.JButton();
        cUF = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cNF.setSelected(true);
        cNF.setText("cNF");

        natOp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        natOp.setSelected(true);
        natOp.setText("natOp");

        mod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mod.setSelected(true);
        mod.setText("mod");

        serie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        serie.setSelected(true);
        serie.setText("serie");

        nNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nNF.setSelected(true);
        nNF.setText("nNF");

        dhEmi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dhEmi.setSelected(true);
        dhEmi.setText("dhEmi");

        idDest.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idDest.setSelected(true);
        idDest.setText("idDest");

        dhSaiEnt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dhSaiEnt.setSelected(true);
        dhSaiEnt.setText("dhSaiEnt");

        tpNF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tpNF.setSelected(true);
        tpNF.setText("tpNF");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Dados de Ide");

        indFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        indFinal.setSelected(true);
        indFinal.setText("indFinal");

        indPres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        indPres.setSelected(true);
        indPres.setText("indPres");

        cMunFG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cMunFG.setSelected(true);
        cMunFG.setText("cMunFG");

        tpImp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tpImp.setSelected(true);
        tpImp.setText("tpImp");

        tpEmis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tpEmis.setSelected(true);
        tpEmis.setText("tpEmis");

        cDV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cDV.setSelected(true);
        cDV.setText("cDV");

        tpAmb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tpAmb.setSelected(true);
        tpAmb.setText("tpAmb");

        finNFe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        finNFe.setSelected(true);
        finNFe.setText("finNFe");

        procEmi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        procEmi.setSelected(true);
        procEmi.setText("procEmi");

        verProc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        verProc.setSelected(true);
        verProc.setText("verProc");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Dados de Prod");

        cProd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cProd.setSelected(true);
        cProd.setText("cProd");

        cEAN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cEAN.setSelected(true);
        cEAN.setText("cEAN");

        xProd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        xProd.setSelected(true);
        xProd.setText("xProd");

        NCM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NCM.setSelected(true);
        NCM.setText("NCM");

        CEST.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CEST.setSelected(true);
        CEST.setText("CEST");

        CFOP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CFOP.setSelected(true);
        CFOP.setText("CFOP");

        qCom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        qCom.setSelected(true);
        qCom.setText("qCom");

        vUnCom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vUnCom.setSelected(true);
        vUnCom.setText("vUnCom");

        vProd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vProd.setSelected(true);
        vProd.setText("vProd");

        cEANTrib.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cEANTrib.setSelected(true);
        cEANTrib.setText("cEANTrib");

        uTrib.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uTrib.setSelected(true);
        uTrib.setText("uTrib");

        qTrib.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        qTrib.setSelected(true);
        qTrib.setText("qTrib");

        uCom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uCom.setSelected(true);
        uCom.setText("uCom");

        vUnTrib.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vUnTrib.setSelected(true);
        vUnTrib.setText("vUnTrib");

        indTot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        indTot.setSelected(true);
        indTot.setText("indTot");

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        cUF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cUF.setSelected(true);
        cUF.setText("cUF");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(natOp)
                            .addComponent(mod)
                            .addComponent(serie)
                            .addComponent(nNF)
                            .addComponent(dhEmi)
                            .addComponent(cNF)
                            .addComponent(dhSaiEnt)
                            .addComponent(tpNF)
                            .addComponent(idDest)
                            .addComponent(cUF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(procEmi)
                            .addComponent(indPres, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(indFinal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(finNFe, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tpAmb, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cDV, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tpEmis, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tpImp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cMunFG, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verProc, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cProd)
                            .addComponent(cEAN)
                            .addComponent(xProd)
                            .addComponent(NCM)
                            .addComponent(CEST)
                            .addComponent(CFOP))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qCom)
                            .addComponent(vUnCom)
                            .addComponent(vProd)
                            .addComponent(qTrib)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cEANTrib)
                                    .addComponent(uTrib))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                                .addComponent(btnEnviar))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(uCom)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(indTot)
                            .addComponent(vUnTrib))))
                .addGap(189, 189, 189))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(cUF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cNF)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(natOp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(serie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nNF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dhEmi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dhSaiEnt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tpNF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idDest))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cMunFG)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(tpImp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tpEmis)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cDV)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tpAmb)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(finNFe)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(indFinal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(indPres))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(qCom)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(vUnCom)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(vProd)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(cEANTrib)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(uTrib)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(btnEnviar)
                                                        .addGap(25, 25, 25)))
                                                .addComponent(qTrib))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cProd)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cEAN)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(xProd)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(NCM)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(CEST)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(CFOP)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(vUnTrib)
                                            .addComponent(uCom))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(indTot)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(procEmi)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(verProc)))
                .addContainerGap(298, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
             
        try 
        {
            ///leitura do xml
            DocumentBuilderFactory dbc = DocumentBuilderFactory.newInstance();
            DocumentBuilder db = dbc.newDocumentBuilder();
            Document doc = db.parse("D:\\Users\\higor\\Documents\\GitHub\\Nfe_XML\\nota.xml");           
            Element raiz = doc.getDocumentElement();
            NodeList nfe = raiz.getChildNodes();
            
            
            ///grava xml
            DocumentBuilderFactory dbcGrava = DocumentBuilderFactory.newInstance();
            DocumentBuilder dbGrava = dbcGrava.newDocumentBuilder();
            Document docXML = dbGrava.newDocument();
            
            for (int i = 0; i < nfe.getLength(); i++) 
            {
                if(nfe.item(i).getNodeName().equals("NFe")) ///entra no Nfe
                {
                    NodeList nfeChild = nfe.item(i).getChildNodes();
                    
                    for (int j = 0; j <nfeChild.getLength() ; j++) 
                    {
                        if(nfeChild.item(j).getNodeName().equals("infNFe")) ///entra no infNfe
                        {                           
                            ///leitura
                            Element element = (Element) nfeChild.item(j);     
                            String id = element.getAttribute("Id");
                            //System.out.println("id :"+id);
                            NodeList infNFeChild = nfeChild.item(j).getChildNodes();
                            
                            ///gravacao root principal e attr id
                            Element infNfeGrava = docXML.createElement("infNfe");
                            docXML.appendChild(infNfeGrava);
                            Attr idGrava = docXML.createAttribute("Id");
                            idGrava.setValue(id);                                        
                            infNfeGrava.setAttributeNode(idGrava);                              
                            
                            for (int k = 0; k < infNFeChild.getLength(); k++) 
                            {
                                
                                if(infNFeChild.item(k).getNodeName().equals("ide")) ///entra no ide
                                {
                                    NodeList ide = infNFeChild.item(k).getChildNodes();
                                    
                                    ///grava ide
                                    Element ideGrava = docXML.createElement("ide");
                                    infNfeGrava.appendChild(ideGrava);
                                    
                                    for (int l = 0; l <ide.getLength() ; l++) 
                                    {
                                        //System.out.println(ide.item(l).getNodeName()+": "+ide.item(l).getTextContent());
                                        
                                        Element ideChildGrava = docXML.createElement(ide.item(l).getNodeName());
                                        
                                        switch(ide.item(l).getNodeName())
                                        {
                                            case "cUF":
                                                if(cUF.isSelected())
                                                {
                                                    ideChildGrava.appendChild(docXML.createTextNode(ide.item(l).getTextContent()));
                                                    ideGrava.appendChild(ideChildGrava);
                                                }
                                                break;
                                            
                                            case "cNF":
                                                if(cNF.isSelected())
                                                {
                                                    ideChildGrava.appendChild(docXML.createTextNode(ide.item(l).getTextContent()));
                                                    ideGrava.appendChild(ideChildGrava);
                                                }
                                                break;
                                                
                                            case "natOp":
                                                if(natOp.isSelected())
                                                {
                                                    ideChildGrava.appendChild(docXML.createTextNode(ide.item(l).getTextContent()));
                                                    ideGrava.appendChild(ideChildGrava);
                                                }
                                                break;
                                            
                                            case "mod":
                                                if(mod.isSelected())
                                                {
                                                    ideChildGrava.appendChild(docXML.createTextNode(ide.item(l).getTextContent()));
                                                    ideGrava.appendChild(ideChildGrava);
                                                }
                                                break;
                                                
                                            case "serie":
                                                if(serie.isSelected())
                                                {
                                                    ideChildGrava.appendChild(docXML.createTextNode(ide.item(l).getTextContent()));
                                                    ideGrava.appendChild(ideChildGrava);
                                                }
                                                break;
                                                
                                            case "nNF":
                                                if(nNF.isSelected())
                                                {
                                                    ideChildGrava.appendChild(docXML.createTextNode(ide.item(l).getTextContent()));
                                                    ideGrava.appendChild(ideChildGrava);
                                                }
                                                break;
                                                
                                            case "dhEmi":
                                                if(dhEmi.isSelected())
                                                {
                                                    ideChildGrava.appendChild(docXML.createTextNode(ide.item(l).getTextContent()));
                                                    ideGrava.appendChild(ideChildGrava);
                                                }
                                                break;
                                                
                                            case "dhSaiEnt":
                                                if(dhSaiEnt.isSelected())
                                                {
                                                    ideChildGrava.appendChild(docXML.createTextNode(ide.item(l).getTextContent()));
                                                    ideGrava.appendChild(ideChildGrava);
                                                }
                                                break;
                                                
                                            case "tpNF":
                                                if(tpNF.isSelected())
                                                {
                                                    ideChildGrava.appendChild(docXML.createTextNode(ide.item(l).getTextContent()));
                                                    ideGrava.appendChild(ideChildGrava);
                                                }
                                                break;
                                                
                                            case "idDest":
                                                if(idDest.isSelected())
                                                {
                                                    ideChildGrava.appendChild(docXML.createTextNode(ide.item(l).getTextContent()));
                                                    ideGrava.appendChild(ideChildGrava);
                                                }
                                                break;
                                                
                                            case "cMunFG":
                                                if(cMunFG.isSelected())
                                                {
                                                    ideChildGrava.appendChild(docXML.createTextNode(ide.item(l).getTextContent()));
                                                    ideGrava.appendChild(ideChildGrava);
                                                }
                                                break;
                                                
                                            case "tpImp":
                                                if(tpImp.isSelected())
                                                {
                                                    ideChildGrava.appendChild(docXML.createTextNode(ide.item(l).getTextContent()));
                                                    ideGrava.appendChild(ideChildGrava);
                                                }
                                                break;
                                                
                                            case "tpEmis":
                                                if(tpEmis.isSelected())
                                                {
                                                    ideChildGrava.appendChild(docXML.createTextNode(ide.item(l).getTextContent()));
                                                    ideGrava.appendChild(ideChildGrava);
                                                }
                                                break;
                                                
                                            case "cDV":
                                                if(cDV.isSelected())
                                                {
                                                    ideChildGrava.appendChild(docXML.createTextNode(ide.item(l).getTextContent()));
                                                    ideGrava.appendChild(ideChildGrava);
                                                }
                                                break;
                                                
                                            case "tpAmb":
                                                if(tpAmb.isSelected())
                                                {
                                                    ideChildGrava.appendChild(docXML.createTextNode(ide.item(l).getTextContent()));
                                                    ideGrava.appendChild(ideChildGrava);
                                                }
                                                break;
                                                
                                            case "finNFe":
                                                if(finNFe.isSelected())
                                                {
                                                    ideChildGrava.appendChild(docXML.createTextNode(ide.item(l).getTextContent()));
                                                    ideGrava.appendChild(ideChildGrava);
                                                }
                                                break;
                                                
                                            case "indFinal":
                                                if(indFinal.isSelected())
                                                {
                                                    ideChildGrava.appendChild(docXML.createTextNode(ide.item(l).getTextContent()));
                                                    ideGrava.appendChild(ideChildGrava);
                                                }
                                                break;
                                                
                                            case "indPres":
                                                if(indPres.isSelected())
                                                {
                                                    ideChildGrava.appendChild(docXML.createTextNode(ide.item(l).getTextContent()));
                                                    ideGrava.appendChild(ideChildGrava);
                                                }
                                                break;
                                                
                                            case "procEmi":
                                                if(procEmi.isSelected())
                                                {
                                                    ideChildGrava.appendChild(docXML.createTextNode(ide.item(l).getTextContent()));
                                                    ideGrava.appendChild(ideChildGrava);
                                                }
                                                break;
                                                
                                            case "verProc":
                                                if(verProc.isSelected())
                                                {
                                                    ideChildGrava.appendChild(docXML.createTextNode(ide.item(l).getTextContent()));
                                                    ideGrava.appendChild(ideChildGrava);
                                                }
                                                break;
                                        }
                                        /*
                                        ///gravacao child ide
                                        Element ideChildGrava = docXML.createElement(ide.item(l).getNodeName());
                                        ideChildGrava.appendChild(docXML.createTextNode(ide.item(l).getTextContent()));
                                        ideGrava.appendChild(ideChildGrava);
                                        */
                                    }
                                }else if(infNFeChild.item(k).getNodeName().equals("det")) ///entra no det
                                {
                                    //leitura
                                    //System.out.println("\n");
                                    Element elementDet = (Element) infNFeChild.item(k);     
                                    String idDet = elementDet.getAttribute("nItem");
                                    //System.out.println("nItem :"+idDet);

                                    NodeList prod = infNFeChild.item(k).getChildNodes();
                                    
                                    //gravacao de det
                                    Element detGrava = docXML.createElement("det");
                                    infNfeGrava.appendChild(detGrava);
                                    Attr nItemGrava = docXML.createAttribute("nItem");
                                    nItemGrava.setValue(idDet);                                        
                                    detGrava.setAttributeNode(nItemGrava);
                                    
                                    
                                    for (int h = 0; h < prod.getLength(); h++) 
                                    {
                                        if(prod.item(h).getNodeName().equals("prod")) ///entra em prod
                                        {                                           
                                            NodeList prodChild = prod.item(h).getChildNodes();
                                            
                                            ///grava prod
                                            Element prodGrava = docXML.createElement("prod");
                                            detGrava.appendChild(prodGrava);
                                            
                                            for (int g = 0; g <prodChild.getLength() ; g++) 
                                            {                
                                                Element prodChildGrava = docXML.createElement(prodChild.item(g).getNodeName());
                                                                                            
                                                //grava prod child
                                                //switch de true ou false dos dados
                                                switch(prodChild.item(g).getNodeName())
                                                {
                                                    case "cProd":
                                                        if(cProd.isSelected())
                                                        {
                                                            prodChildGrava.appendChild(docXML.createTextNode(prodChild.item(g).getTextContent()));
                                                            prodGrava.appendChild(prodChildGrava);
                                                        }
                                                        break;
                                                        
                                                    case "cEAN":
                                                        if(cEAN.isSelected())
                                                        {
                                                            prodChildGrava.appendChild(docXML.createTextNode(prodChild.item(g).getTextContent()));
                                                            prodGrava.appendChild(prodChildGrava);
                                                        }
                                                        break;
                                                        
                                                    case "xProd":
                                                        if(xProd.isSelected())
                                                        {
                                                            prodChildGrava.appendChild(docXML.createTextNode(prodChild.item(g).getTextContent()));
                                                            prodGrava.appendChild(prodChildGrava);
                                                        }
                                                        break;
                                                        
                                                    case "NCM":
                                                        if(NCM.isSelected())
                                                        {
                                                            prodChildGrava.appendChild(docXML.createTextNode(prodChild.item(g).getTextContent()));
                                                            prodGrava.appendChild(prodChildGrava);
                                                        }
                                                        break;
                                                        
                                                    case "CEST":
                                                        if(CEST.isSelected())
                                                        {
                                                            prodChildGrava.appendChild(docXML.createTextNode(prodChild.item(g).getTextContent()));
                                                            prodGrava.appendChild(prodChildGrava);
                                                        }
                                                        break;
                                                        
                                                    case "CFOP":
                                                        if(CFOP.isSelected())
                                                        {
                                                            prodChildGrava.appendChild(docXML.createTextNode(prodChild.item(g).getTextContent()));
                                                            prodGrava.appendChild(prodChildGrava);
                                                        }
                                                        break;
                                                        
                                                    case "uCom":
                                                        if(uCom.isSelected())
                                                        {
                                                            prodChildGrava.appendChild(docXML.createTextNode(prodChild.item(g).getTextContent()));
                                                            prodGrava.appendChild(prodChildGrava);
                                                        }
                                                        break;
                                                    
                                                    case "qCom":
                                                        if(qCom.isSelected())
                                                        {
                                                            prodChildGrava.appendChild(docXML.createTextNode(prodChild.item(g).getTextContent()));
                                                            prodGrava.appendChild(prodChildGrava);
                                                        }
                                                        break;
                                                        
                                                    case "vUnCom":
                                                        if(vUnCom.isSelected())
                                                        {
                                                            prodChildGrava.appendChild(docXML.createTextNode(prodChild.item(g).getTextContent()));
                                                            prodGrava.appendChild(prodChildGrava);
                                                        }
                                                        break;
                                                        
                                                    case "vProd":
                                                        if(vProd.isSelected())
                                                        {
                                                            prodChildGrava.appendChild(docXML.createTextNode(prodChild.item(g).getTextContent()));
                                                            prodGrava.appendChild(prodChildGrava);
                                                        }
                                                        break;
                                                        
                                                    case "cEANTrib":
                                                        if(cEANTrib.isSelected())
                                                        {
                                                            prodChildGrava.appendChild(docXML.createTextNode(prodChild.item(g).getTextContent()));
                                                            prodGrava.appendChild(prodChildGrava);
                                                        }
                                                        break;
                                                        
                                                    case "uTrib":
                                                        if(uTrib.isSelected())
                                                        {
                                                            prodChildGrava.appendChild(docXML.createTextNode(prodChild.item(g).getTextContent()));
                                                            prodGrava.appendChild(prodChildGrava);
                                                        }
                                                        break;
                                                        
                                                    case "qTrib":
                                                        if(qTrib.isSelected())
                                                        {
                                                            prodChildGrava.appendChild(docXML.createTextNode(prodChild.item(g).getTextContent()));
                                                            prodGrava.appendChild(prodChildGrava);
                                                        }
                                                        break;
                                                        
                                                    case "vUnTrib":
                                                        if(vUnTrib.isSelected())
                                                        {
                                                            prodChildGrava.appendChild(docXML.createTextNode(prodChild.item(g).getTextContent()));
                                                            prodGrava.appendChild(prodChildGrava);
                                                        }
                                                        break;
                                                        
                                                    case "indTot":
                                                        if(indTot.isSelected())
                                                        {
                                                            prodChildGrava.appendChild(docXML.createTextNode(prodChild.item(g).getTextContent()));
                                                            prodGrava.appendChild(prodChildGrava);
                                                        }
                                                        break;
                                                        
                                                        
                                                }
                                                /*///grava child de prod
                                                Element prodChildGrava = docXML.createElement(prodChild.item(g).getNodeName());
                                                prodChildGrava.appendChild(docXML.createTextNode(prodChild.item(g).getTextContent()));
                                                prodGrava.appendChild(prodChildGrava);
                                                //System.out.println(prodChild.item(g).getNodeName()+": "+prodChild.item(g).getTextContent());
                                                */
                                            }
                                        }                                            
                                    }                                                                          
                                }                                                                                 
                            }
                        }                        
                    }
                }
            }
            
            TransformerFactory tf = TransformerFactory.newInstance();
            Transformer t = tf.newTransformer();
            
            DOMSource docFonte =  new DOMSource(docXML);
            StreamResult docFinal = new StreamResult(new File("D:\\Users\\higor\\Documents\\GitHub\\Nfe_XML\\teste.xml"));
            
            t.transform(docFonte, docFinal);

        } catch (ParserConfigurationException | SAXException | IOException ex) 
        {
            Logger.getLogger(Nfe_XML.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerConfigurationException ex) {
            Logger.getLogger(Nfe_XML.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(Nfe_XML.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null, "Arquivo XML criado");
        
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CEST;
    private javax.swing.JCheckBox CFOP;
    private javax.swing.JCheckBox NCM;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JCheckBox cDV;
    private javax.swing.JCheckBox cEAN;
    private javax.swing.JCheckBox cEANTrib;
    private javax.swing.JCheckBox cMunFG;
    private javax.swing.JCheckBox cNF;
    private javax.swing.JCheckBox cProd;
    private javax.swing.JCheckBox cUF;
    private javax.swing.JCheckBox dhEmi;
    private javax.swing.JCheckBox dhSaiEnt;
    private javax.swing.JCheckBox finNFe;
    private javax.swing.JCheckBox idDest;
    private javax.swing.JCheckBox indFinal;
    private javax.swing.JCheckBox indPres;
    private javax.swing.JCheckBox indTot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox mod;
    private javax.swing.JCheckBox nNF;
    private javax.swing.JCheckBox natOp;
    private javax.swing.JCheckBox procEmi;
    private javax.swing.JCheckBox qCom;
    private javax.swing.JCheckBox qTrib;
    private javax.swing.JCheckBox serie;
    private javax.swing.JCheckBox tpAmb;
    private javax.swing.JCheckBox tpEmis;
    private javax.swing.JCheckBox tpImp;
    private javax.swing.JCheckBox tpNF;
    private javax.swing.JCheckBox uCom;
    private javax.swing.JCheckBox uTrib;
    private javax.swing.JCheckBox vProd;
    private javax.swing.JCheckBox vUnCom;
    private javax.swing.JCheckBox vUnTrib;
    private javax.swing.JCheckBox verProc;
    private javax.swing.JCheckBox xProd;
    // End of variables declaration//GEN-END:variables
}
